modified NetworkDevice.ps1 to allow snmp parameters
PowerAruba/PowerArubaCP pull request #76
Opened 2023-11-17 19:28 UTC by staley1975

Allows adding network devices (nads) with SNMP parameters, and setting SNMP parameters to existing network devices (nads)

2023-11-17 20:22 UTC, alagoutte commented
Hi @staley1975 

Thanks for your contribution, it is possible to add some test (on Tests/integration/NetworkDevice.Tests.ps1) ?

2023-11-17 20:48 UTC, alagoutte requested changes

2023-11-17 20:48 UTC, alagoutte commented on PowerArubaCP/Public/NetworkDevice.ps1
> +        [string]$snmp_version,
Use ValidateSet v1/v2c ?

2023-11-17 20:48 UTC, alagoutte commented on PowerArubaCP/Public/NetworkDevice.ps1
> +        if ($PsBoundParameters.ContainsKey('snmp_version')) {
if community_string is empty ?

2023-11-17 20:48 UTC, alagoutte commented on PowerArubaCP/Public/NetworkDevice.ps1
> +            snmp_version = $snmp_version
add 4space (for align)

```
$snmp_read = @{
    snmp_version = $snmp_version
    community_string....
```

2023-11-18 08:47 UTC, alagoutte commented
can you also look for test ?

may be also move example to the end (and use SW6 ?)

2023-11-19 14:26 UTC, alagoutte commented
Thanks, i will try and merge if it is ok

2023-11-19 15:38 UTC, staley1975 commented
> Thanks, i will try and merge if it is ok

Sounds good, and thank you for the feedback.

2023-12-08 14:08 UTC, alagoutte commented
> > Thanks, i will try and merge if it is ok
> 
> Sounds good, and thank you for the feedback.

Tested with 6.11 and 6.12 ! Working !

Thanks for your contribution, it will publish a new release on some next week...

2023-12-08 14:08 UTC, merged